In [1]:
import pandas as pd
import numpy as np
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")
my_stopwords = nlp.Defaults.stop_words

In [3]:
spam = pd.read_csv('../data/spam.csv', encoding = "ISO-8859-1", engine = "python").drop(columns=["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])

In [4]:
spam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [5]:
Y = spam["v1"]
X = spam["v2"]

In [6]:
for i in range(len(X)):
    x = X.iloc[i]
    tokens = nlp(x)
    cleared_words = [token for token in tokens if token.lower_ not in my_stopwords and not token.is_punct and not token.like_num]
    lemma_words = [word.lemma_ for word in cleared_words]
    X.iloc[i] = ' '.join(lemma_words)

# 1. Самостоятельно реализовать BoW, TF-IDF

## Bag of Words

In [8]:
import sys
sys.path.insert(0, "C://Users//MSI//Desktop//OmSTU//MachineLearning//models//Words")
from sklearn.feature_extraction.text import CountVectorizer
from bagofwordsModel import BoWModel

In [9]:
texts = np.array(spam.sample(10)["v2"])
texts

array(['Today sunday sunday holiday work', 'oh ho time u use type word',
       'pain come bad time', 'depend like treat',
       'future plan tomorrow result today good present enjoy future',
       'Ill min look', 'Sos pls', 'hi dude hw r u da realy mise u today',
       'not thnk wrong calling',
       'sea lay rock rock envelope envelope paper paper word'],
      dtype=object)

In [10]:
cv = CountVectorizer()

In [11]:
bow = cv.fit_transform(texts)
print(bow.todense())

[[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1
  0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 1 1 1 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1
  1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 2 1 0 0 0 0 0
  0 0 0 0 1 0 0]]


In [12]:
cv.vocabulary_

{'today': 35,
 'sunday': 32,
 'holiday': 12,
 'work': 41,
 'oh': 21,
 'ho': 11,
 'time': 34,
 'use': 39,
 'type': 38,
 'word': 40,
 'pain': 22,
 'come': 2,
 'bad': 0,
 'depend': 4,
 'like': 16,
 'treat': 37,
 'future': 8,
 'plan': 24,
 'tomorrow': 36,
 'result': 28,
 'good': 9,
 'present': 26,
 'enjoy': 6,
 'ill': 14,
 'min': 18,
 'look': 17,
 'sos': 31,
 'pls': 25,
 'hi': 10,
 'dude': 5,
 'hw': 13,
 'da': 3,
 'realy': 27,
 'mise': 19,
 'not': 20,
 'thnk': 33,
 'wrong': 42,
 'calling': 1,
 'sea': 30,
 'lay': 15,
 'rock': 29,
 'envelope': 7,
 'paper': 23}

In [13]:
bow.shape

(10, 43)

In [14]:
bowmodel = BoWModel()
bow = bowmodel.fit_transfrom(texts)
bow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 

In [17]:
bowmodel.vocabulary

{'today': 35,
 'sunday': 32,
 'holiday': 12,
 'work': 41,
 'oh': 21,
 'ho': 11,
 'time': 34,
 'use': 39,
 'type': 38,
 'word': 40,
 'pain': 22,
 'come': 2,
 'bad': 0,
 'depend': 4,
 'like': 16,
 'treat': 37,
 'future': 8,
 'plan': 24,
 'tomorrow': 36,
 'result': 28,
 'good': 9,
 'present': 26,
 'enjoy': 6,
 'ill': 14,
 'min': 18,
 'look': 17,
 'sos': 31,
 'pls': 25,
 'hi': 10,
 'dude': 5,
 'hw': 13,
 'da': 3,
 'realy': 27,
 'mise': 19,
 'not': 20,
 'thnk': 33,
 'wrong': 42,
 'calling': 1,
 'sea': 30,
 'lay': 15,
 'rock': 29,
 'envelope': 7,
 'paper': 23}

In [18]:
bow.shape

(10, 43)

## TF-IDF

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from tfidfModel import TF_IDFModel

In [20]:
tfidfsk = TfidfVectorizer()
tfidf = tfidfsk.fit_transform(texts)
tfidf.shape

(10, 43)

In [21]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.3906389 , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.7812778 , 0.        , 0.        ,
         0.29052967, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.3906389 , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.42853734, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.42853734, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 

In [22]:
tfidfsk.vocabulary_

{'today': 35,
 'sunday': 32,
 'holiday': 12,
 'work': 41,
 'oh': 21,
 'ho': 11,
 'time': 34,
 'use': 39,
 'type': 38,
 'word': 40,
 'pain': 22,
 'come': 2,
 'bad': 0,
 'depend': 4,
 'like': 16,
 'treat': 37,
 'future': 8,
 'plan': 24,
 'tomorrow': 36,
 'result': 28,
 'good': 9,
 'present': 26,
 'enjoy': 6,
 'ill': 14,
 'min': 18,
 'look': 17,
 'sos': 31,
 'pls': 25,
 'hi': 10,
 'dude': 5,
 'hw': 13,
 'da': 3,
 'realy': 27,
 'mise': 19,
 'not': 20,
 'thnk': 33,
 'wrong': 42,
 'calling': 1,
 'sea': 30,
 'lay': 15,
 'rock': 29,
 'envelope': 7,
 'paper': 23}

In [23]:
tfidfmy = TF_IDFModel()
tfidf = tfidfmy.fit_transform(texts)
tfidf.shape

(10, 43)

In [24]:
tfidf

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.3906389 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.7812778 , 0.        , 0.        ,
        0.29052967, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3906389 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.42853734, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.42853734, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
   

In [25]:
tfidfmy.vocabulary

{'today': 35,
 'sunday': 32,
 'holiday': 12,
 'work': 41,
 'oh': 21,
 'ho': 11,
 'time': 34,
 'use': 39,
 'type': 38,
 'word': 40,
 'pain': 22,
 'come': 2,
 'bad': 0,
 'depend': 4,
 'like': 16,
 'treat': 37,
 'future': 8,
 'plan': 24,
 'tomorrow': 36,
 'result': 28,
 'good': 9,
 'present': 26,
 'enjoy': 6,
 'ill': 14,
 'min': 18,
 'look': 17,
 'sos': 31,
 'pls': 25,
 'hi': 10,
 'dude': 5,
 'hw': 13,
 'da': 3,
 'realy': 27,
 'mise': 19,
 'not': 20,
 'thnk': 33,
 'wrong': 42,
 'calling': 1,
 'sea': 30,
 'lay': 15,
 'rock': 29,
 'envelope': 7,
 'paper': 23}

# 2. Решить задачу классификации с понижением размерности. Использовать самостоятельно реализованные модели из предыдущих ЛР.

In [43]:
Y = Y.replace({"ham" : 0, "spam" : 1})

In [44]:
X = TfidfVectorizer().fit_transform(X).todense()
X.shape

(5572, 7108)

In [45]:
sys.path.insert(0, "C://Users//MSI//Desktop//OmSTU//MachineLearning//models//Classification")
sys.path.insert(0, "C://Users//MSI//Desktop//OmSTU//MachineLearning//models//Downsizing")

from knn import KNearestNeighborsModel
from pcamodel import PCAModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

In [46]:
pca = PCAModel(n_components = 3500)
X = pca.fit_transform(np.array(X))
X.shape

(5572, 3500)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)

In [48]:
X_train.shape

(5014, 3500)

In [49]:
knn = KNearestNeighborsModel(n_neighbors = 1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [50]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.99      0.94      0.96       514
           1       0.55      0.93      0.69        44

    accuracy                           0.94       558
   macro avg       0.77      0.93      0.83       558
weighted avg       0.96      0.94      0.94       558



# 3. Решить задачу мягкой кластеризации (ТМ) с помощью LDA

In [26]:
from sklearn.decomposition import LatentDirichletAllocation

In [27]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))

In [34]:
cv = CountVectorizer()
tf = cv.fit_transform(spam["v2"])

In [37]:
lda = LatentDirichletAllocation(n_components=5, max_iter=25, 
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0).fit(tf)

In [38]:
print_top_words(lda, cv.get_feature_names_out(), 7)

Topic #0:
free text txt mobile ur reply stop
Topic #1:
cash reach holiday camera urgent speak prize
Topic #2:
gt lt hi hey like yes get
Topic #3:
go come not ok know get want
Topic #4:
day ur send dear pls happy love
